version: "3.7"
services:
  public_api:
    build:
      context: ../
      dockerfile: app/services/public/Dockerfile
    restart: always
    volumes:
      - ../log/public:/home/comely-io/public/log
      - ../emails:/home/comely-io/public/emails
      - ../storage:/home/comely-io/public/storage
      - ../tmp:/home/comely-io/public/tmp
      - ../app/services/public/vendor:/home/comely-io/public/vendor
    env_file:
      - .env
    environment:
      COMELY_APP_CACHED_CONFIG: "true"
    ports:
      - "${PUBLIC_PORT}:6000"
    networks:
      comely-app-vlan:
        ipv4_address: 10.0.20.13

# Networks Configuration
networks:
  comely-app-vlan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.20.0/27
