# Databases Configuration
# Primary database ID/Node
primary:
  driver: mysql
  host: 10.0.20.2
  port: ~ # Leave NULL for default port
  name: primary # It is recommended to NOT change this name
  username: root # If built DB service, default username is "root"
  password: ~ # If built DB service, it will automatically pick root password
# Public API Sessions/Log
api_log:
  driver: mysql
  host: 10.0.20.2
  port: ~ # Leave NULL for default port
  name: api_logs # It is recommended to NOT change this name
  username: root # If built DB service, default username is "root"
  password: ~ # If built DB service, it will automatically pick root password
